apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-eap-o8xk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-eap-o8xk
    app.kubernetes.io/part-of: rhtap-eap
  name: rhtap-eap-o8xk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtap-eap-o8xk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtap-eap-o8xk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/phayes1-tenant/rhtap-eap/rhtap-eap-o8xk@sha256:d0b8ddc5d92de04d12aa9f5c36e1f1d18804dd0dc0b4ae87f95ae59bd7f46134
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
