apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-eap-o8xk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-eap-o8xk
    app.kubernetes.io/part-of: rhtap-eap
  name: rhtap-eap-o8xk
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: rhtap-eap-o8xk
status:
  loadBalancer: {}
