apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-eap-o8xk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/phayes1-tenant/rhtap-eap/rhtap-eap-o8xk@sha256:e2141ad2ee2304ccad41e85e8bd40ae34297f5950827d8719edd5162466527fc
        name: container-image
        resources: {}
status: {}
