apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-eap-o8xk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-eap-o8xk
    app.kubernetes.io/part-of: rhtap-eap
  name: rhtap-eap-o8xkcixd
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhtap-eap-o8xk
    weight: 100
status: {}
